stages:          # List of stages for jobs, and their order of execution
  - test
  - deploy

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Tests passed"
  only:
    - dev

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - (docker ps -a --format {{.Names}} | grep tbot -w) && docker stop tbot && docker rm tbot || echo "Doesn't exist"
    - docker build -t java-tbot:1.0 .
    - docker run --name=tbot -d -p 8087:8087 -t java-tbot:1.0
    - docker system prune -a
  only:
    - dev
